{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "36414999-bf02-4dc5-9fb3-b4dfc7a9631a",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "import os\n",
    "import json\n",
    "import gradio as gr\n",
    "from databricks.sdk import WorkspaceClient\n",
    "from databricks.sdk.service.serving import ChatMessage, ChatMessageRole\n",
    "\n",
    "# ============= CONFIGURATION =============\n",
    "LLM_ENDPOINT = \"databricks-llama-4-maverick\"  # Working endpoint!\n",
    "SARVAM_API_KEY = os.environ.get(\"SARVAM_API_KEY\", \"\")\n",
    "\n",
    "# Load pre-aggregated mandi data (NO SQL CONNECTION NEEDED!)\n",
    "MANDI_DATA = []\n",
    "try:\n",
    "    data_path = os.path.join(os.path.dirname(__file__), \"mandi_data.json\")\n",
    "    with open(data_path, 'r') as f:\n",
    "        MANDI_DATA = json.load(f)\n",
    "    print(f\"✅ Loaded {len(MANDI_DATA)} mandi records from cache\")\n",
    "except Exception as e:\n",
    "    print(f\"⚠️ Could not load mandi data: {e}\")\n",
    "\n",
    "# Initialize Databricks client\n",
    "try:\n",
    "    w = WorkspaceClient()\n",
    "    print(\"✅ Databricks client initialized\")\n",
    "except Exception as e:\n",
    "    print(f\"⚠️ Databricks client initialization failed: {e}\")\n",
    "    w = None\n",
    "\n",
    "LANG_REPLY_INSTRUCTION = {\n",
    "    \"English\": \"Reply in English.\",\n",
    "    \"Hinglish\": \"Reply in Romanized Hindi (Latin script).\",\n",
    "    \"हिन्दी\": \"Reply in Hindi (Devanagari script).\",\n",
    "    \"தமிழ்\": \"Reply in Tamil.\",\n",
    "    \"తెలుగు\": \"Reply in Telugu.\",\n",
    "    \"मराठी\": \"Reply in Marathi.\",\n",
    "    \"বাংলা\": \"Reply in Bengali.\",\n",
    "    \"ਪੰਜਾਬੀ\": \"Reply in Punjabi (Gurmukhi script).\",\n",
    "}\n",
    "\n",
    "# ============= UI TRANSLATIONS =============\n",
    "UI_TRANSLATIONS = {\n",
    "    \"English\": {\n",
    "        \"title\": \"🌾 Mandi Mitra — AI Agricultural Advisor\",\n",
    "        \"subtitle\": \"*Ask about crop prices and best mandis in any Indian language!*\",\n",
    "        \"powered_by\": \"<small>Powered by: Llama 4 Maverick + Pre-computed Mandi Data</small>\",\n",
    "        \"lang_label\": \"Language\",\n",
    "        \"district_label\": \"District\",\n",
    "        \"quintals_label\": \"Quintals\",\n",
    "        \"question_label\": \"⌨️ Type your question\",\n",
    "        \"question_placeholder\": \"Where should I sell onions?\",\n",
    "        \"submit_button\": \"Ask Mandi Mitra ➤\",\n",
    "        \"response_label\": \"🤖 Mandi Mitra says\",\n",
    "        \"examples_header\": \"### Example Questions:\",\n",
    "        \"example_1\": \"- Where should I sell onions in my district?\",\n",
    "        \"example_2\": \"- What is the current tomato price in Nashik?\",\n",
    "        \"example_3\": \"- Best market for potatoes near me?\",\n",
    "    },\n",
    "    \"Hinglish\": {\n",
    "        \"title\": \"🌾 Mandi Mitra — AI Kheti Salahkar\",\n",
    "        \"subtitle\": \"*Kisi bhi Indian bhasha mein fasal ki keemat aur best mandi ke baare mein poochiye!*\",\n",
    "        \"powered_by\": \"<small>Powered by: Llama 4 Maverick + Pre-computed Mandi Data</small>\",\n",
    "        \"lang_label\": \"Bhasha / Language\",\n",
    "        \"district_label\": \"Zila / District\",\n",
    "        \"quintals_label\": \"Quintal\",\n",
    "        \"question_label\": \"⌨️ Apna sawal likhiye\",\n",
    "        \"question_placeholder\": \"Pyaaz kahan bechun?\",\n",
    "        \"submit_button\": \"Mandi Mitra se Poochiye ➤\",\n",
    "        \"response_label\": \"🤖 Mandi Mitra ka Jawab\",\n",
    "        \"examples_header\": \"### Example Sawal:\",\n",
    "        \"example_1\": \"- Mujhe pyaaz kahan bechna chahiye?\",\n",
    "        \"example_2\": \"- Nashik mein tamatar ka price kya hai?\",\n",
    "        \"example_3\": \"- Aaloo ke liye best mandi konsi hai?\",\n",
    "    },\n",
    "    \"हिन्दी\": {\n",
    "        \"title\": \"🌾 मंडी मित्र — एआई कृषि सलाहकार\",\n",
    "        \"subtitle\": \"*किसी भी भारतीय भाषा में फसल की कीमत और सर्वोत्तम मंडी के बारे में पूछें!*\",\n",
    "        \"powered_by\": \"<small>संचालित: Llama 4 Maverick + पूर्व-संगणित मंडी डेटा</small>\",\n",
    "        \"lang_label\": \"भाषा\",\n",
    "        \"district_label\": \"जिला\",\n",
    "        \"quintals_label\": \"क्विंटल\",\n",
    "        \"question_label\": \"⌨️ अपना प्रश्न लिखें\",\n",
    "        \"question_placeholder\": \"प्याज कहाँ बेचूं?\",\n",
    "        \"submit_button\": \"मंडी मित्र से पूछें ➤\",\n",
    "        \"response_label\": \"🤖 मंडी मित्र का उत्तर\",\n",
    "        \"examples_header\": \"### उदाहरण प्रश्न:\",\n",
    "        \"example_1\": \"- मुझे प्याज कहाँ बेचना चाहिए?\",\n",
    "        \"example_2\": \"- नासिक में टमाटर की कीमत क्या है?\",\n",
    "        \"example_3\": \"- आलू के लिए सबसे अच्छी मंडी कौन सी है?\",\n",
    "    },\n",
    "    \"தமிழ்\": {\n",
    "        \"title\": \"🌾 மண்டி மித்ரா — AI விவசாய ஆலோசகர்\",\n",
    "        \"subtitle\": \"*எந்த இந்திய மொழியிலும் பயிர் விலைகள் மற்றும் சிறந்த மண்டிகள் பற்றி கேளுங்கள்!*\",\n",
    "        \"powered_by\": \"<small>இயக்குபவர்: Llama 4 Maverick + முன்கணிக்கப்பட்ட மண்டி தரவு</small>\",\n",
    "        \"lang_label\": \"மொழி\",\n",
    "        \"district_label\": \"மாவட்டம்\",\n",
    "        \"quintals_label\": \"குவிண்டால்கள்\",\n",
    "        \"question_label\": \"⌨️ உங்கள் கேள்வியை தட்டச்சு செய்யவும்\",\n",
    "        \"question_placeholder\": \"வெங்காயத்தை எங்கே விற்க வேண்டும்?\",\n",
    "        \"submit_button\": \"மண்டி மித்ராவிடம் கேளுங்கள் ➤\",\n",
    "        \"response_label\": \"🤖 மண்டி மித்ரா கூறுகிறார்\",\n",
    "        \"examples_header\": \"### உதாரண கேள்விகள்:\",\n",
    "        \"example_1\": \"- நான் வெங்காயத்தை எங்கே விற்க வேண்டும்?\",\n",
    "        \"example_2\": \"- நாசிக்கில் தக்காளி விலை என்ன?\",\n",
    "        \"example_3\": \"- உருளைக்கிழங்குக்கு சிறந்த சந்தை எது?\",\n",
    "    },\n",
    "    \"తెలుగు\": {\n",
    "        \"title\": \"🌾 మండి మిత్ర — AI వ్యవసాయ సలహాదారు\",\n",
    "        \"subtitle\": \"*ఏ భారతీయ భాషలోనైనా పంట ధరలు మరియు ఉత్తమ మండీల గురించి అడగండి!*\",\n",
    "        \"powered_by\": \"<small>శక్తిచేత: Llama 4 Maverick + ముందస్తు మండి డేటా</small>\",\n",
    "        \"lang_label\": \"భాష\",\n",
    "        \"district_label\": \"జిల్లా\",\n",
    "        \"quintals_label\": \"క్వింటాల్స్\",\n",
    "        \"question_label\": \"⌨️ మీ ప్రశ్నను టైప్ చేయండి\",\n",
    "        \"question_placeholder\": \"ఉల్లిపాయలను ఎక్కడ అమ్మాలి?\",\n",
    "        \"submit_button\": \"మండి మిత్రను అడగండి ➤\",\n",
    "        \"response_label\": \"🤖 మండి మిత్ర చెప్పేది\",\n",
    "        \"examples_header\": \"### ఉదాహరణ ప్రశ్నలు:\",\n",
    "        \"example_1\": \"- నేను ఉల్లిపాయలను ఎక్కడ అమ్మాలి?\",\n",
    "        \"example_2\": \"- నాసిక్‌లో టమోటా ధర ఎంత?\",\n",
    "        \"example_3\": \"- బంగాళదుంపల కోసం ఉత్తమ మార్కెట్ ఏది?\",\n",
    "    },\n",
    "    \"मराठी\": {\n",
    "        \"title\": \"🌾 मंडी मित्र — AI कृषी सल्लागार\",\n",
    "        \"subtitle\": \"*कोणत्याही भारतीय भाषेत पिकांच्या किमती आणि सर्वोत्तम मंडी बद्दल विचारा!*\",\n",
    "        \"powered_by\": \"<small>चालविले: Llama 4 Maverick + पूर्व-गणना केलेला मंडी डेटा</small>\",\n",
    "        \"lang_label\": \"भाषा\",\n",
    "        \"district_label\": \"जिल्हा\",\n",
    "        \"quintals_label\": \"क्विंटल\",\n",
    "        \"question_label\": \"⌨️ तुमचा प्रश्न टाइप करा\",\n",
    "        \"question_placeholder\": \"कांदे कुठे विकावे?\",\n",
    "        \"submit_button\": \"मंडी मित्राला विचारा ➤\",\n",
    "        \"response_label\": \"🤖 मंडी मित्र सांगतो\",\n",
    "        \"examples_header\": \"### उदाहरण प्रश्न:\",\n",
    "        \"example_1\": \"- मला कांदे कुठे विकावे?\",\n",
    "        \"example_2\": \"- नाशिकमध्ये टोमॅटोची किंमत किती आहे?\",\n",
    "        \"example_3\": \"- बटाट्यांसाठी सर्वोत्तम मार्केट कोणती?\",\n",
    "    },\n",
    "    \"বাংলা\": {\n",
    "        \"title\": \"🌾 মান্ডি মিত্র — AI কৃষি পরামর্শদাতা\",\n",
    "        \"subtitle\": \"*যেকোনো ভারতীয় ভাষায় ফসলের দাম এবং সেরা মান্ডি সম্পর্কে জিজ্ঞাসা করুন!*\",\n",
    "        \"powered_by\": \"<small>চালিত: Llama 4 Maverick + পূর্ব-গণনা করা মান্ডি ডেটা</small>\",\n",
    "        \"lang_label\": \"ভাষা\",\n",
    "        \"district_label\": \"জেলা\",\n",
    "        \"quintals_label\": \"কুইন্টাল\",\n",
    "        \"question_label\": \"⌨️ আপনার প্রশ্ন টাইপ করুন\",\n",
    "        \"question_placeholder\": \"পেঁয়াজ কোথায় বিক্রি করব?\",\n",
    "        \"submit_button\": \"মান্ডি মিত্রকে জিজ্ঞাসা করুন ➤\",\n",
    "        \"response_label\": \"🤖 মান্ডি মিত্র বলছেন\",\n",
    "        \"examples_header\": \"### উদাহরণ প্রশ্ন:\",\n",
    "        \"example_1\": \"- আমি পেঁয়াজ কোথায় বিক্রি করব?\",\n",
    "        \"example_2\": \"- নাসিকে টমেটোর দাম কত?\",\n",
    "        \"example_3\": \"- আলুর জন্য সেরা বাজার কোনটি?\",\n",
    "    },\n",
    "    \"ਪੰਜਾਬੀ\": {\n",
    "        \"title\": \"🌾 ਮੰਡੀ ਮਿੱਤਰ — AI ਖੇਤੀ ਸਲਾਹਕਾਰ\",\n",
    "        \"subtitle\": \"*ਕਿਸੇ ਵੀ ਭਾਰਤੀ ਭਾਸ਼ਾ ਵਿੱਚ ਫਸਲਾਂ ਦੀਆਂ ਕੀਮਤਾਂ ਅਤੇ ਸਭ ਤੋਂ ਵਧੀਆ ਮੰਡੀਆਂ ਬਾਰੇ ਪੁੱਛੋ!*\",\n",
    "        \"powered_by\": \"<small>ਸੰਚਾਲਿਤ: Llama 4 Maverick + ਪਹਿਲਾਂ ਤੋਂ ਗਣਨਾ ਕੀਤਾ ਮੰਡੀ ਡੇਟਾ</small>\",\n",
    "        \"lang_label\": \"ਭਾਸ਼ਾ\",\n",
    "        \"district_label\": \"ਜ਼ਿਲ੍ਹਾ\",\n",
    "        \"quintals_label\": \"ਕੁਇੰਟਲ\",\n",
    "        \"question_label\": \"⌨️ ਆਪਣਾ ਸਵਾਲ ਟਾਈਪ ਕਰੋ\",\n",
    "        \"question_placeholder\": \"ਪਿਆਜ਼ ਕਿੱਥੇ ਵੇਚਣੇ ਚਾਹੀਦੇ ਹਨ?\",\n",
    "        \"submit_button\": \"ਮੰਡੀ ਮਿੱਤਰ ਨੂੰ ਪੁੱਛੋ ➤\",\n",
    "        \"response_label\": \"🤖 ਮੰਡੀ ਮਿੱਤਰ ਕਹਿੰਦਾ ਹੈ\",\n",
    "        \"examples_header\": \"### ਉਦਾਹਰਨ ਸਵਾਲ:\",\n",
    "        \"example_1\": \"- ਮੈਂ ਪਿਆਜ਼ ਕਿੱਥੇ ਵੇਚਣੇ ਚਾਹੀਦੇ ਹਨ?\",\n",
    "        \"example_2\": \"- ਨਾਸਿਕ ਵਿੱਚ ਟਮਾਟਰ ਦੀ ਕੀਮਤ ਕੀ ਹੈ?\",\n",
    "        \"example_3\": \"- ਆਲੂਆਂ ਲਈ ਸਭ ਤੋਂ ਵਧੀਆ ਮੰਡੀ ਕਿਹੜੀ ਹੈ?\",\n",
    "    },\n",
    "}\n",
    "\n",
    "# ============= HELPER FUNCTIONS =============\n",
    "\n",
    "def llm_query(messages, timeout=30):\n",
    "    \"\"\"Query LLM with timeout and error handling\"\"\"\n",
    "    if not w:\n",
    "        return \"LLM service unavailable\"\n",
    "    \n",
    "    try:\n",
    "        # Convert dict messages to ChatMessage objects\n",
    "        chat_messages = []\n",
    "        for msg in messages:\n",
    "            role = ChatMessageRole.SYSTEM if msg[\"role\"] == \"system\" else ChatMessageRole.USER\n",
    "            chat_messages.append(ChatMessage(role=role, content=msg[\"content\"]))\n",
    "        \n",
    "        response = w.serving_endpoints.query(\n",
    "            name=LLM_ENDPOINT,\n",
    "            messages=chat_messages,\n",
    "            max_tokens=512\n",
    "        )\n",
    "        return response.choices[0].message.content\n",
    "    except Exception as e:\n",
    "        print(f\"LLM query error: {e}\")\n",
    "        return f\"LLM Error: {str(e)}\"\n",
    "\n",
    "def query_mandi_data(crop, district, limit=3):\n",
    "    \"\"\"Query pre-loaded mandi data (NO DATABASE CONNECTION!)\"\"\"\n",
    "    crop = crop.lower().strip()\n",
    "    district = district.lower().strip()\n",
    "    \n",
    "    # Filter data\n",
    "    results = [\n",
    "        r for r in MANDI_DATA \n",
    "        if r.get(\"commodity\", \"\").lower() == crop \n",
    "        and r.get(\"district_name\", \"\").lower() == district\n",
    "    ]\n",
    "    \n",
    "    # Sort by avg_price descending and take top N\n",
    "    results = sorted(results, key=lambda x: x.get(\"avg_price\", 0), reverse=True)[:limit]\n",
    "    \n",
    "    return results\n",
    "\n",
    "def extract_intent(user_query):\n",
    "    \"\"\"Extract crop and district from user query using LLM\"\"\"\n",
    "    sys_prompt = \"\"\"You are a JSON extractor for an Indian agriculture app.\n",
    "From the user's message (in ANY language):\n",
    "1. Extract the crop name. Translate to English lowercase. Valid: tomato, onion, potato, wheat. Else null.\n",
    "2. Extract the district in English lowercase. If not mentioned, null.\n",
    "Return ONLY valid JSON: {\"crop\":\"...\",\"district\":\"...\"}\"\"\"\n",
    "    \n",
    "    try:\n",
    "        raw = llm_query([\n",
    "            {\"role\": \"system\", \"content\": sys_prompt},\n",
    "            {\"role\": \"user\", \"content\": user_query}\n",
    "        ], timeout=15)\n",
    "        \n",
    "        # Clean up response\n",
    "        raw = raw.strip().replace(\"```json\", \"\").replace(\"```\", \"\").strip()\n",
    "        return json.loads(raw)\n",
    "    except Exception as e:\n",
    "        print(f\"Intent extraction error: {e}\")\n",
    "        return {\"crop\": None, \"district\": None}\n",
    "\n",
    "def normalize_district(raw_district, lang):\n",
    "    \"\"\"Normalize district name\"\"\"\n",
    "    if lang in (\"English\", \"Hinglish\"):\n",
    "        return raw_district.strip().lower()\n",
    "    \n",
    "    try:\n",
    "        result = llm_query([\n",
    "            {\"role\": \"system\", \"content\": \"Translate this Indian district name to English. Return ONLY the English district name in lowercase, nothing else.\"},\n",
    "            {\"role\": \"user\", \"content\": raw_district}\n",
    "        ], timeout=10)\n",
    "        return result.strip().lower()\n",
    "    except:\n",
    "        return raw_district.strip().lower()\n",
    "\n",
    "def generate_reply(user_query, data_context, lang):\n",
    "    \"\"\"Generate natural language response\"\"\"\n",
    "    lang_instruction = LANG_REPLY_INSTRUCTION.get(lang, \"Reply in the same language as the user.\")\n",
    "    sys_prompt = f\"\"\"You are Mandi Mitra, a friendly Indian agricultural advisor.\n",
    "Data context:\n",
    "{data_context}\n",
    "\n",
    "Rules:\n",
    "- {lang_instruction}\n",
    "- Be concise (2-4 sentences). Use ₹ for prices.\n",
    "- If data is missing, say which crops are supported: tomato, onion, potato, wheat.\n",
    "- End with \"Jai Kisan!\" or its equivalent in the reply language.\"\"\"\n",
    "    \n",
    "    try:\n",
    "        return llm_query([\n",
    "            {\"role\": \"system\", \"content\": sys_prompt},\n",
    "            {\"role\": \"user\", \"content\": user_query}\n",
    "        ])\n",
    "    except Exception as e:\n",
    "        return f\"⚠️ Response generation error: {e}\"\n",
    "\n",
    "def get_mandi_predictions(crop, district, quintals=10):\n",
    "    \"\"\"Get mandi predictions from cached data\"\"\"\n",
    "    results = query_mandi_data(crop, district, limit=3)\n",
    "    \n",
    "    if not results:\n",
    "        return None\n",
    "    \n",
    "    # Add net return calculation\n",
    "    for r in results:\n",
    "        r[\"net_return\"] = (r[\"avg_price\"] * quintals) - 250\n",
    "    \n",
    "    return results\n",
    "\n",
    "# ============= MAIN CHATBOT LOGIC =============\n",
    "\n",
    "def chatbot_logic(user_query, raw_district, quintals, lang):\n",
    "    \"\"\"Main chatbot logic - NO SQL CONNECTIONS!\"\"\"\n",
    "    if not user_query or not user_query.strip():\n",
    "        return \"Please type a question.\"\n",
    "    \n",
    "    # Step 1: Normalize district\n",
    "    district_en = normalize_district(raw_district, lang)\n",
    "    \n",
    "    # Step 2: Extract intent (crop, district)\n",
    "    intent = extract_intent(user_query)\n",
    "    \n",
    "    if not intent or not intent.get(\"crop\"):\n",
    "        ctx = \"No specific crop detected. Supported crops: tomato, onion, potato, wheat.\"\n",
    "        return generate_reply(user_query, ctx, lang)\n",
    "    \n",
    "    crop = intent[\"crop\"]\n",
    "    district = intent.get(\"district\") or district_en\n",
    "    \n",
    "    # Step 3: Query cached data\n",
    "    results = get_mandi_predictions(crop, district, quintals)\n",
    "    \n",
    "    if not results:\n",
    "        ctx = f\"Crop: {crop}, District: {district}. No data found in our records.\"\n",
    "    else:\n",
    "        top = results[0]\n",
    "        names = \", \".join([r[\"market_center\"].title() for r in results])\n",
    "        ctx = (f\"Crop: {crop}, District: {district}\\n\"\n",
    "               f\"Top mandi: {top['market_center'].title()} at ₹{round(top['avg_price'], 2)}/quintal\\n\"\n",
    "               f\"Estimated profit for {quintals}q: ₹{round(top['net_return'], 2)}\\n\"\n",
    "               f\"Options: {names}\")\n",
    "    \n",
    "    # Step 4: Generate natural language reply\n",
    "    return generate_reply(user_query, ctx, lang)\n",
    "\n",
    "# ============= UI UPDATE FUNCTION =============\n",
    "\n",
    "def update_ui_language(selected_lang):\n",
    "    \"\"\"Update all UI elements based on selected language\"\"\"\n",
    "    translations = UI_TRANSLATIONS.get(selected_lang, UI_TRANSLATIONS[\"English\"])\n",
    "    \n",
    "    return [\n",
    "        gr.update(label=translations[\"lang_label\"]),  # lang dropdown\n",
    "        gr.update(label=translations[\"district_label\"]),  # district textbox\n",
    "        gr.update(label=translations[\"quintals_label\"]),  # quintals number\n",
    "        gr.update(label=translations[\"question_label\"], placeholder=translations[\"question_placeholder\"]),  # text_in\n",
    "        gr.update(value=translations[\"submit_button\"]),  # submit button\n",
    "        gr.update(label=translations[\"response_label\"]),  # reply_out\n",
    "    ]\n",
    "\n",
    "# ============= GRADIO UI =============\n",
    "\n",
    "def handle_text(text, district, quintals, lang):\n",
    "    \"\"\"Handle text input\"\"\"\n",
    "    try:\n",
    "        return chatbot_logic(text, district, int(quintals), lang)\n",
    "    except Exception as e:\n",
    "        return f\"❌ Error: {str(e)}\"\n",
    "\n",
    "with gr.Blocks(title=\"🌾 Mandi Mitra\", theme=gr.themes.Soft()) as demo:\n",
    "    # Dynamic title and subtitle (updated via JavaScript)\n",
    "    title_md = gr.Markdown(\"## 🌾 Mandi Mitra — AI Agricultural Advisor\")\n",
    "    subtitle_md = gr.Markdown(\"*Ask about crop prices and best mandis in any Indian language!*\")\n",
    "    powered_md = gr.Markdown(\"<small>Powered by: Llama 4 Maverick + Pre-computed Mandi Data</small>\")\n",
    "    \n",
    "    with gr.Row():\n",
    "        lang = gr.Dropdown(\n",
    "            choices=list(LANG_REPLY_INSTRUCTION.keys()), \n",
    "            value=\"हिन्दी\", \n",
    "            label=\"भाषा / Language\"\n",
    "        )\n",
    "        district = gr.Textbox(value=\"pune\", label=\"जिला / District\")\n",
    "        quintals = gr.Number(value=10, label=\"क्विंटल / Quintals\", minimum=1)\n",
    "    \n",
    "    text_in = gr.Textbox(\n",
    "        label=\"⌨️ अपना प्रश्न लिखें\", \n",
    "        placeholder=\"प्याज कहाँ बेचूं?\",\n",
    "        lines=2\n",
    "    )\n",
    "    submit_btn = gr.Button(\"मंडी मित्र से पूछें ➤\", variant=\"primary\")\n",
    "    reply_out = gr.Textbox(label=\"🤖 मंडी मित्र का उत्तर\", interactive=False, lines=6)\n",
    "    \n",
    "    examples_md = gr.Markdown(\"### उदाहरण प्रश्न:\")\n",
    "    example1_md = gr.Markdown(\"- मुझे प्याज कहाँ बेचना चाहिए?\")\n",
    "    example2_md = gr.Markdown(\"- नासिक में टमाटर की कीमत क्या है?\")\n",
    "    example3_md = gr.Markdown(\"- आलू के लिए सबसे अच्छी मंडी कौन सी है?\")\n",
    "    \n",
    "    # Language change updates UI\n",
    "    lang.change(\n",
    "        fn=update_ui_language,\n",
    "        inputs=[lang],\n",
    "        outputs=[lang, district, quintals, text_in, submit_btn, reply_out]\n",
    "    )\n",
    "    \n",
    "    # Also update title/subtitle/examples when language changes\n",
    "    def update_text_elements(selected_lang):\n",
    "        translations = UI_TRANSLATIONS.get(selected_lang, UI_TRANSLATIONS[\"English\"])\n",
    "        return [\n",
    "            gr.update(value=f\"## {translations['title']}\"),\n",
    "            gr.update(value=translations['subtitle']),\n",
    "            gr.update(value=translations['powered_by']),\n",
    "            gr.update(value=translations['examples_header']),\n",
    "            gr.update(value=translations['example_1']),\n",
    "            gr.update(value=translations['example_2']),\n",
    "            gr.update(value=translations['example_3']),\n",
    "        ]\n",
    "    \n",
    "    lang.change(\n",
    "        fn=update_text_elements,\n",
    "        inputs=[lang],\n",
    "        outputs=[title_md, subtitle_md, powered_md, examples_md, example1_md, example2_md, example3_md]\n",
    "    )\n",
    "    \n",
    "    # Submit button action\n",
    "    submit_btn.click(\n",
    "        fn=handle_text,\n",
    "        inputs=[text_in, district, quintals, lang],\n",
    "        outputs=[reply_out]\n",
    "    )\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    demo.launch(server_name=\"0.0.0.0\", server_port=8000)"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "5"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "New Notebook 2026-04-08 16_39_04",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
